name: soundpool_macos
description: A Flutter Sound Pool for playing short audio files. Sound tracks are cached in memory and played directly from cache.
version: 0.2.5
homepage: https://github.com/ukasz123/soundpool/tree/master/soundpool_macos


environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"
  
dependencies:
  flutter:
    sdk: flutter

  soundpool_platform_interface:
    git: 
      url: https://github.com/gongqinjing/soundpool.git
      ref: efeaa962c2627ea82f6c442f57ed6eb46123b47b
      path: soundpool_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: SwiftSoundpoolPlugin
