name: soundpool
description: A Flutter Sound Pool for playing short audio files. Sound tracks are cached in memory and played directly from cache.
version: 1.1.2
homepage: https://github.com/ukasz123/soundpool/tree/master/soundpool

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  soundpool_platform_interface:
    git: 
      url: https://github.com/gongqinjing/soundpool.git
      ref: efeaa962c2627ea82f6c442f57ed6eb46123b47b
      path: soundpool_platform_interface
  
  soundpool_web:
    git:
      url: https://github.com/gongqinjing/soundpool.git
      ref: dccda3ac6b01d002aa57241263c5169e4a8ef4c6
      path: soundpool_web
  
  soundpool_macos:
    git:
      url: https://github.com/gongqinjing/soundpool.git
      ref: 6a198bd1f819f1a6ac7b9148c931c04b6fd2ea6b
      path: soundpool_macos
    
    
flutter:
  plugin:
    platforms:
      android:
        package: pl.ukaszapps.soundpool
        pluginClass: SoundpoolPlugin
      ios:
        pluginClass: SoundpoolPlugin
      web:
        default_package: soundpool_web 
      macos:
        default_package: soundpool_macos
